CREATE TABLE User (
  idUser INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  login VARCHAR(80) NOT NULL ,
  password VARCHAR(80) NOT NULL ,
  dateInsert TIMESTAMP NOT NULL ,
  dateLastAccess TIMESTAMP,
  name VARCHAR(80) NOT NULL ,
  email VARCHAR(100)
  ) ENGINE=InnoDB;
  
  CREATE UNIQUE INDEX User_login_IDX ON User(login);