INSERT INTO Clube (nome, bandeira) VALUES('Áfica do Sul','AficaDoSul.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Alemanha','Alemanha.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Argélia','Argelia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Argentina','Argentina.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Austrália','Australia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Brasil','Brasil.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Camarões','Camaroes.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Chile','Chile.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Coréia do Norte','CoreiaDoNorte.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Coréia do Sul','CoreiaDoSul.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Costa do Marfim','CostaDoMarfim.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Dinamarca','Dinamarca.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Eslováquia','Eslovaquia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Eslovénia','Eslovenia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Espanha','Espanha.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Estados Unidos','EstadosUnidos.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Françaa','Franca.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Gana','Gana.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Grácia','Grecia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Holanda','Holanda.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Honduras','Honduras.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Inglaterra','Inglaterra.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Itália','Italia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Japão','Japao.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('México','Mexico.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Nigéria','Nigeria.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Nova Zelândia','NovaZelandia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Paraguai','Paraguai.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Portugal','Portugal.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Sérvia','Servia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Suíça','Suica.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Uruguai','Uruguai.jpg');