INSERT INTO Clube (idclube, nome, bandeira) VALUES(1,'Alemanha','bandeiras/Alemanha.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(2,'Argélia','bandeiras/Argelia.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(3,'Argentina','bandeiras/Argentina.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(4,'Austrália','bandeiras/Australia.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(5,'Brasil','bandeiras/Brasil.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(6,'Belgica','bandeiras/Belgica.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(7,'Bosnia','bandeiras/Bosnia.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(8,'Camarões','bandeiras/Camaroes.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(9,'Chile','bandeiras/Chile.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(10,'Colombia','bandeiras/Colombia.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(11,'Coréia do Sul','bandeiras/CoreiaDoSul.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(12,'Costa do Marfim','bandeiras/CostaDoMarfim.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(13,'Costa Rica','bandeiras/CostaRica.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(14,'Croácia','bandeiras/Croacia.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(15,'Equador','bandeiras/Equador.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(16,'Espanha','bandeiras/Espanha.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(17,'Estados Unidos','bandeiras/USA.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(18,'França','bandeiras/Franca.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(19,'Gana','bandeiras/Gana.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(20,'Grecia','bandeiras/Grecia.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(21,'Holanda','bandeiras/Holanda.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(22,'Honduras','bandeiras/Honduras.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(23,'Inglaterra','bandeiras/Inglaterra.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(24,'Irã','bandeiras/Ira.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(25,'Itália','bandeiras/Italia.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(26,'Japão','bandeiras/Japao.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(27,'México','bandeiras/Mexico.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(28,'Nigéria','bandeiras/Nigeria.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(29,'Portugal','bandeiras/Portugal.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(30,'Russia','bandeiras/Russia.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(31,'Suíça','bandeiras/Suica.png');
INSERT INTO Clube (idclube, nome, bandeira) VALUES(32,'Uruguai','bandeiras/Uruguai.png');