INSERT INTO Clube (nome, bandeira) VALUES('África do Sul','bandeiras/AficaDoSul.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Alemanha','bandeiras/Alemanha.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Argélia','bandeiras/Argelia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Argentina','bandeiras/Argentina.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Austrália','bandeiras/Australia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Brasil','bandeiras/Brasil.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Camarões','bandeiras/Camaroes.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Chile','bandeiras/Chile.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Coréia do Norte','bandeiras/CoreiaDoNorte.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Coréia do Sul','bandeiras/CoreiaDoSul.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Costa do Marfim','bandeiras/CostaDoMarfim.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Dinamarca','bandeiras/Dinamarca.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Eslováquia','bandeiras/Eslovaquia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Eslovénia','bandeiras/Eslovenia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Espanha','bandeiras/Espanha.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Estados Unidos','bandeiras/EstadosUnidos.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Françaa','bandeiras/Franca.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Gana','bandeiras/Gana.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Grecia','bandeiras/Grecia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Holanda','bandeiras/Holanda.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Honduras','bandeiras/Honduras.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Inglaterra','bandeiras/Inglaterra.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Itália','bandeiras/Italia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Japão','bandeiras/Japao.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('México','bandeiras/Mexico.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Nigéria','bandeiras/Nigeria.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Nova Zelândia','bandeiras/NovaZelandia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Paraguai','bandeiras/Paraguai.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Portugal','bandeiras/Portugal.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Sérvia','bandeiras/Servia.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Suíça','bandeiras/Suica.jpg');
INSERT INTO Clube (nome, bandeira) VALUES('Uruguai','bandeiras/Uruguai.jpg');